name: Backend test
on:
  push:
    branches: [main, signin/signupfix]
  pull_request:
    branches: [main]

# defaults:
#   run:
#     working-directory: ../backend

jobs:
  build:
    name: backend-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/
    
    steps:
      - name: backend-test
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: './backend/package-lock.json'

      - run: npm ci # similar to npm install
      - run: npm run build --if-present
      - run: npm test
