name: Backend test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: backend-test
    runs-on: ubuntu-latest
    
    steps:
      - name: backend-test
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci # similar to npm install
      - run: npm run build --if-present
      - run: npm test
